version: '3.8'

services:
  bobcoperation-website:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      - NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
      - NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  # Opcional: Base de datos PostgreSQL para futuras funcionalidades
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: bobcoperation
  #     POSTGRES_USER: bobcoperation
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # Opcional: Redis para caché
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  redis_data:
